nginx.yml
---
- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: "create www directory"
    file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: clone preconfigured index.html files
    git:
      repo: https://github.com/KofiSQ/Nuspire/blob/main/index.html
      dest: /etc/nginx/sites-enabled
  - name: clone preconfigured site.conf.j2
    git:
      repo: https://github.com/KofiSQ/Nuspire/blob/main/site.conf.j2
      dest: /etc/ngix/sites-enabled

  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
      notify: restart nginx

  - name: copy nginx site.conf
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
      notify: restart nginx

  - handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restart nginx
  - name: Install PostgreSQL
       yum: name=postgresql state=latest
       tags: PostgreSQL

  - name: Start PostgreSQL
      service:
      name: postgresql
      state: started
  - name: install Git client
       yum: 
         name: Git
         state: present
